name: Main Branch

on:
  push:
    branches:
      - 'main'
jobs:
    compile:
        name : "Compile project"
        runs-on: ubuntu-18.04
        steps:
          - uses: actions/checkout@v1
          - name: Set up JDK 11
            uses: actions/setup-java@v1
            with:
              java-version: 11.0.4
          - name: Maven compile
            run: mvn compile
    test:
        name : "Unit Test"
        runs-on: ubuntu-18.04
        steps:
          - uses: actions/checkout@v1
          - name: Set up JDK 11
            uses: actions/setup-java@v1
            with:
              java-version: 11.0.4
          - name: Maven test command
            run: mvn test
    build:
        name : "Build project"
        runs-on: ubuntu-18.04
        steps:
          - uses: actions/checkout@v1
          - name: Set up JDK 11
            uses: actions/setup-java@v1
            with:
              java-version: 11.0.4
          - name: Maven test command
            run: mvn install
    
    upload-artifact:
        name : "upload-artifact"
        runs-on: ubuntu-18.04
        steps:
          - uses: actions/checkout@v3

          - uses: actions/setup-java@v3

            with:
              java-version: '11'
              distribution: 'adopt'
          - run: mvn --batch-mode --update-snapshots verify
          - run: mkdir staging && cp target/*.jar staging
          - uses: actions/upload-artifact@v3
            with:
              name: Package
              path: staging
              
    docker:
        name : "Building docker image"
        runs-on: ubuntu-18.04
        environment: dev
        steps:
          - uses: actions/checkout@v1
          - name: Docker login
            run: docker login -u ${{secrets.DOCKER_USER_NAME}} -p ${{secrets.DOCKER_PASSWORD}} 
          - name: Build and tag docker image
            run: docker build -t sathishkumar281995/github-action-demo .
          - name: Docker push
            run: docker push sathishkumar281995/github-action-demo